import type { EngineComponents } from '../engine/LiveCodingEngine'

/**
 * A user-authored visualization saved to IndexedDB.
 * Compiled to a VizDescriptor at runtime for use with .viz("name").
 */
export interface CropRegion {
  /** Fractional offset from left (0–1). */
  x: number
  /** Fractional offset from top (0–1). */
  y: number
  /** Fractional width (0–1). */
  w: number
  /** Fractional height (0–1). */
  h: number
}

export interface VizPreset {
  id: string
  name: string
  renderer: 'hydra' | 'p5'
  code: string
  requires: (keyof EngineComponents)[]
  createdAt: number
  updatedAt: number
  /** Optional crop region for inline viz display. Fractional 0–1 coords
   *  relative to the full canvas. When set, the inline zone shows only
   *  this sub-region (scaled to fill). */
  cropRegion?: CropRegion
  /** Native canvas dimensions the sketch renders at. If absent, the
   *  default (1200×600) is used. Set this when your sketch calls
   *  createCanvas(W, H) with specific values you want the inline viz
   *  to respect — the crop region is interpreted in these coords. */
  nativeSize?: { w: number; h: number }
}

// ---------------------------------------------------------------------------
// IndexedDB Store
// ---------------------------------------------------------------------------

const DB_NAME = 'stave-viz-presets'
const DB_VERSION = 1
const STORE_NAME = 'presets'

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION)
    req.onupgradeneeded = () => {
      const db = req.result
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: 'id' })
      }
    }
    req.onsuccess = () => resolve(req.result)
    req.onerror = () => reject(req.error)
  })
}

function tx(
  db: IDBDatabase,
  mode: IDBTransactionMode,
): IDBObjectStore {
  return db.transaction(STORE_NAME, mode).objectStore(STORE_NAME)
}

function wrap<T>(req: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result)
    req.onerror = () => reject(req.error)
  })
}

// ---------------------------------------------------------------------------
// ID generation
// ---------------------------------------------------------------------------

/**
 * Reserved prefix for app-bundled demo presets. User-created IDs cannot
 * start with this — guaranteed by `generateUniquePresetId`'s sanitizer
 * which strips leading underscores.
 */
export const BUNDLED_PREFIX = '__bundled_'

/**
 * Sanitize a display name into an ID-safe slug:
 *   "My Aurora!"  →  "my_aurora"
 *   "  spaces  "  →  "spaces"
 *   ""            →  "untitled"
 */
export function sanitizePresetName(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
  return slug || 'untitled'
}

/**
 * Build the ID for an app-bundled preset:
 *   bundledPresetId('Piano Roll', 'p5')  →  '__bundled_piano_roll_p5__'
 *
 * Bundled IDs never collide with user IDs because user IDs follow the
 * `<name>_<renderer>_v<N>` format and never start with `__`.
 */
export function bundledPresetId(name: string, renderer: 'hydra' | 'p5'): string {
  return `${BUNDLED_PREFIX}${sanitizePresetName(name)}_${renderer}__`
}

/** True if this id was generated by `bundledPresetId`. */
export function isBundledPresetId(id: string): boolean {
  return id.startsWith(BUNDLED_PREFIX)
}

/**
 * Generate a unique user preset ID in the format `<name>_<renderer>_v<N>`,
 * where N is the smallest positive integer such that the resulting id is
 * not present in `existingIds`.
 *
 * Examples (with no collisions):
 *   ('Piano Roll',  'p5',    [])  →  'piano_roll_p5_v1'
 *   ('Piano Roll',  'hydra', [])  →  'piano_roll_hydra_v1'
 *
 * With collisions:
 *   ('Piano Roll',  'p5',    ['piano_roll_p5_v1'])  →  'piano_roll_p5_v2'
 */
export function generateUniquePresetId(
  name: string,
  renderer: 'hydra' | 'p5',
  existingIds: Iterable<string>,
): string {
  const slug = sanitizePresetName(name)
  const used = new Set(existingIds)
  let n = 1
  let id = `${slug}_${renderer}_v${n}`
  while (used.has(id)) {
    n++
    id = `${slug}_${renderer}_v${n}`
  }
  return id
}

export const VizPresetStore = {
  async getAll(): Promise<VizPreset[]> {
    const db = await openDb()
    return wrap<VizPreset[]>(tx(db, 'readonly').getAll())
  },

  async get(id: string): Promise<VizPreset | undefined> {
    const db = await openDb()
    return wrap<VizPreset | undefined>(tx(db, 'readonly').get(id))
  },

  async put(preset: VizPreset): Promise<void> {
    const db = await openDb()
    await wrap(tx(db, 'readwrite').put(preset))
  },

  async delete(id: string): Promise<void> {
    const db = await openDb()
    await wrap(tx(db, 'readwrite').delete(id))
  },
}
