import type * as Monaco from 'monaco-editor'

export function defineStrudelMonacoTheme(monaco: typeof Monaco): void {
  monaco.editor.defineTheme('stave-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'strudel.pattern-start', foreground: '7c7cff', fontStyle: 'bold' },
      { token: 'strudel.tempo',         foreground: 'a78bfa' },
      { token: 'strudel.function',      foreground: '93c5fd' },
      { token: 'strudel.note',          foreground: '86efac' },
      { token: 'strudel.mini.note',     foreground: '86efac' },
      { token: 'strudel.mini.operator', foreground: 'f472b6' },
      { token: 'strudel.mini.number',   foreground: 'fb923c' },
      { token: 'string',                foreground: 'fcd34d' },
      { token: 'string.escape',         foreground: 'fde68a' },
      { token: 'string.quote',          foreground: 'fcd34d' },
      { token: 'number',                foreground: 'fb923c' },
      { token: 'number.hex',            foreground: 'fb923c' },
      { token: 'number.binary',         foreground: 'fb923c' },
      { token: 'number.float',          foreground: 'fb923c' },
      { token: 'comment',               foreground: '6b7280', fontStyle: 'italic' },
      { token: 'keyword',               foreground: 'c4b5fd' },
      { token: 'keyword.operator',      foreground: 'f472b6' },
      { token: 'variable.predefined',   foreground: 'fde68a' },
      { token: 'constant',              foreground: 'fb923c' },
      { token: 'type',                  foreground: '7dd3fc' },
      { token: 'identifier',            foreground: 'e2e8f0' },
      { token: 'identifier.property',   foreground: '93c5fd' },
      { token: 'delimiter',             foreground: '94a3b8' },
      { token: 'delimiter.parenthesis', foreground: '94a3b8' },
      { token: 'delimiter.curly',       foreground: '94a3b8' },
      { token: 'delimiter.square',      foreground: '94a3b8' },
      { token: 'delimiter.bracket',     foreground: '94a3b8' },
      // Sonic Pi tokens
      { token: 'sonicpi.function',      foreground: '93c5fd', fontStyle: 'bold' },
      { token: 'sonicpi.music',         foreground: 'a78bfa' },
      { token: 'sonicpi.symbol',        foreground: 'f472b6' },
      { token: 'sonicpi.note',          foreground: '86efac' },
      { token: 'sonicpi.kwarg',         foreground: '6ee7b7' },
    ],
    colors: {
      'editor.background':              '#090912',
      'editor.foreground':              '#c4b5fd',
      'editorLineNumber.foreground':    '#3d3d5c',
      'editorCursor.foreground':        '#7c7cff',
      'editor.selectionBackground':     '#6a6ac840',
      'editor.lineHighlightBackground': '#6a6ac80d',
      'editorIndentGuide.background':   '#ffffff10',
      'editorWidget.background':        '#0f0f1e',
      'editorSuggestWidget.background': '#0f0f1e',
      'editorSuggestWidget.border':     '#6a6ac840',
      'minimap.background':             '#00000000',
    },
  })

  monaco.editor.defineTheme('stave-light', {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'strudel.pattern-start', foreground: '4a4ae0', fontStyle: 'bold' },
      { token: 'strudel.tempo',         foreground: '5555b8' },
      { token: 'strudel.function',      foreground: '1d4ed8' },
      { token: 'strudel.note',          foreground: '15803d' },
      { token: 'strudel.mini.note',     foreground: '15803d' },
      { token: 'strudel.mini.operator', foreground: 'be185d' },
      { token: 'strudel.mini.number',   foreground: 'c2410c' },
      { token: 'string',                foreground: '92400e' },
      { token: 'string.escape',         foreground: 'a16207' },
      { token: 'string.quote',          foreground: '92400e' },
      { token: 'number',                foreground: 'c2410c' },
      { token: 'number.hex',            foreground: 'c2410c' },
      { token: 'number.binary',         foreground: 'c2410c' },
      { token: 'number.float',          foreground: 'c2410c' },
      { token: 'comment',               foreground: '9ca3af', fontStyle: 'italic' },
      { token: 'keyword',               foreground: '6d28d9' },
      { token: 'keyword.operator',      foreground: 'be185d' },
      { token: 'variable.predefined',   foreground: '92400e' },
      { token: 'constant',              foreground: 'c2410c' },
      { token: 'type',                  foreground: '0369a1' },
      { token: 'identifier',            foreground: '1e1b4b' },
      { token: 'identifier.property',   foreground: '1d4ed8' },
      { token: 'delimiter',             foreground: '64748b' },
      { token: 'delimiter.parenthesis', foreground: '64748b' },
      { token: 'delimiter.curly',       foreground: '64748b' },
      { token: 'delimiter.square',      foreground: '64748b' },
      { token: 'delimiter.bracket',     foreground: '64748b' },
    ],
    colors: {
      'editor.background':              '#f0f0f6',
      'editor.foreground':              '#1e1b4b',
      'editorLineNumber.foreground':    '#a0a0b4',
      'editorCursor.foreground':        '#4a4ae0',
      'editor.selectionBackground':     '#5555b830',
      'editor.lineHighlightBackground': '#5555b808',
      'minimap.background':             '#00000000',
    },
  })
}
